import { DataTypes } from 'sequelize';

export default (sequelize) => {
  const Transaction = sequelize.define('Transaction', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'users', // Matches the User table
        key: 'id'
      }
    },
    type: {
      type: DataTypes.ENUM('ONRAMP', 'OFFRAMP'),
      allowNull: false,
    },
    status: {
      type: DataTypes.ENUM(
        'INITIATED',       // row created, before Paystack call made
        'PROMPT_SENT',     // Paystack returned 200, STK push delivered
        'PAID',            // Paystack confirmed charge.success (webhook or reconciliation)
        'PAYOUT_QUEUED',   // payout job enqueued, Circle not yet called
        'PAYOUT_SENT',     // Circle confirmed transfer
        'COMPLETE',        // Circle confirmed on-chain completion (txHash available)
        'FAILED',          // charge.failed or STK timeout, before payment received
        'PAYOUT_FAILED'    // payment received but Circle send failed — critical state
      ),
      defaultValue: 'INITIATED',
    },
    fiatAmount: {
      type: DataTypes.DECIMAL(10, 2), // e.g., 1500.50 KES
      allowNull: false,
    },
    fiatCurrency: {
      type: DataTypes.STRING(3),
      defaultValue: 'KES', // Defaulting to Kenyan Shilling
    },
    cryptoAmount: {
      type: DataTypes.DECIMAL(18, 6), // 6 decimals for USDC
      allowNull: false,
    },
    cryptoCurrency: {
      type: DataTypes.STRING(10),
      defaultValue: 'USDC',
    },
    exchangeRate: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      comment: "The locked FX rate at the time of transaction (e.g., 1 USDC = 130 KES)"
    },
    paystackReference: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Reference ID generated by Paystack"
    },
    circleTxId: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Reference ID generated by Circle Developer Controlled Wallets API"
    },
    txHash: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Blockchain transaction hash from Base Sepolia"
    },
    walletAddress: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "The destination/source wallet address for the crypto"
    },
    cryptoNetwork: {
      type: DataTypes.STRING,
      allowNull: true,
      defaultValue: 'Base Sepolia',
      comment: "The blockchain network used"
    },
    failureReason: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: "Populated on FAILED or PAYOUT_FAILED"
    },
    paidAt: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: "Timestamp when payment was confirmed received"
    },
    payoutSentAt: {
      type: DataTypes.DATE,
      allowNull: true,
      comment: "Timestamp when Circle payout was successfully executed"
    }
  }, {
    tableName: 'transactions',
    timestamps: true,
    indexes: [
      {
        unique: true,
        fields: ['paystackReference']
      },
      {
        unique: true,
        fields: ['txHash']
      }
    ]
  });

  return Transaction;
};