const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Transaction = sequelize.define('Transaction', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'users', // Matches the User table
        key: 'id'
      }
    },
    type: {
      type: DataTypes.ENUM('ONRAMP', 'OFFRAMP'),
      allowNull: false,
    },
    status: {
      type: DataTypes.ENUM(
        'PENDING',           // User clicked buy/sell
        'FIAT_PROCESSING',   // Paystack prompt sent
        'FIAT_RECEIVED',     // Paystack successful
        'CRYPTO_PROCESSING', // Circle transaction sent to blockchain
        'COMPLETED',         // Entire bridge is done
        'FAILED',            // Something went wrong
        'REFUNDED'           // Failed and money sent back
      ),
      defaultValue: 'PENDING',
    },
    fiatAmount: {
      type: DataTypes.DECIMAL(10, 2), // e.g., 1500.50 KES
      allowNull: false,
    },
    fiatCurrency: {
      type: DataTypes.STRING(3),
      defaultValue: 'KES', // Defaulting to Kenyan Shilling
    },
    cryptoAmount: {
      type: DataTypes.DECIMAL(18, 6), // 6 decimals for USDC
      allowNull: false,
    },
    cryptoCurrency: {
      type: DataTypes.STRING(10),
      defaultValue: 'USDC',
    },
    exchangeRate: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      comment: "The locked FX rate at the time of transaction (e.g., 1 USDC = 130 KES)"
    },
    paystackReference: {
      type: DataTypes.STRING,
      allowNull: true,
      unique: true,
      comment: "Reference ID generated by Paystack"
    },
    txHash: {
      type: DataTypes.STRING,
      allowNull: true,
      unique: true,
      comment: "Blockchain transaction hash from Base Sepolia"
    }
  }, {
    tableName: 'transactions',
    timestamps: true,
  });

  return Transaction;
};